### ISSUE TITLE
This plugin disables the settings button + ... this plugin doesn't do anything. 

### ISSUE THREAD

**Issue by DotScott1** [OllisGit/OctoPrint-PauseAt#3]
As soon as I install this plugin, the settings button gets disabled. It's still there, just clicking on it does nothing. The only way I can get back into settings is to restart octoprint in safe mode, go to settings and disable this plugin (then the settings button will work in the regular mode again). 

Additionally: I've tried everything I can think of to get the height part to work (Pause at: 4mm height. Pause script: replace nut. Resume script: replace nut. Doesn't do anything. 

Unfortunate :/ Was really looking forward to using this plugin.

**Comment by piotre15** [comment]
Hi together
exact the same to me...
Thanks Dotscott1 for the detailed descreption.

You will make me so happy fixing this ;-)

**Comment by OllisGit** [comment]
@DotScott1 @piotre15 
This plugin is not released yet! (see startpage "work in progress").

My goal is to finish this plugin till end of March 2019.

**Comment by piotre15** [comment]
Dear @OllisGit 
Thank you very much for your wonderfull feedback.
I'm really excited because instead of nuts I'm going to put small magnets in my prints to keep them together.
Have a great happy new year!
Peter

**Comment by DotScott1** [comment]
Hey that's actually exactly the same thing I'm doing! :D Magnets. I did end
up getting it to pause at a certain height just by scripting it in
Simplify3D. Anyway, looking forward to when this one works! I think it'll
be a great tool!

**Comment by R0dri** [comment]
> @DotScott1 @piotre15
> This plugin is not released yet! (see startpage "work in progress").
> 
> My goal is to finish this plugin till end of March 2019.

soo... will this be finished anytime?

**Comment by OllisGit** [comment]
@R0dri  --> hopfully!

In the last weeks I did some additional preparations for this plugin:
- New Plugin "https://github.com/OllisGit/OctoPrint-DryRun" now I can test the plugin-development without heating and wasting fillament
- Send layer-/height informations from my other plugin to the eventbus, so that the "Pause-Plugin" could work with it (https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/tag/1.11.0)

...and some other "conceptual work"....it is not easy to implement, because there are so many options and technical "hurdles".
See some discussion in the Octoprint-Forum:
https://community.octoprint.org/t/the-safe-gcodes-for-afterprintpaused-and-beforeprintresumed-hooks/8462/2
https://community.octoprint.org/t/better-pause-function-in-octoprint/5331/4

Thats the reason that no one already released a plugin ;-)

The best approach today is to use your slicer-software.

BUT:
I will start releasing a beta-version with limited features, e.g. pause only on height-value instead of layer in the next week.

**Comment by Monberg75** [comment]
did you release the plugin? I just activated the plugin with the settings button disabled as result. :(

**Comment by OllisGit** [comment]
Hi @Monberg75 ,

sorry for the delayed answer, but the auto-notification was disabled for this repository.
More details, see 
https://community.octoprint.org/t/pause-at-layer-end/1412/30
